config/routes.rb
Rails.application.routes.draw do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    resource :registration
    resource :session
    resource :password_reset
    resource :password


  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

   # Defines the root path route ("/")
   root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  attribute :role, :integer, default: 0

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :firstname, presence: true
  validates :lastname, presence: true

  enum role: { user: 0, admin: 1, moderator: 2 }

  after_initialize :set_default_role, if: :new_record?

  normalizes :email, with: ->(email) { email.strip.downcase }
  generates_token_for :password_reset, expires_in: 15.minutes do
    password_salt&.last(10)
  end
  generates_token_for :email_confirmation, expires_in: 24.hours do
    email
  end

  private

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
private

def authenticate_user!
  redirect_to root_path, alert: "You must be logged in to do that." unless  user_signed_in?
end

def current_user
  Current.user ||= authenticate_user_from_session
end
helper_method :current_user
def authenticate_user_from_session
User.find_by(id: session[:user_id])
end

def user_signed_in?
  current_user.present?
end
helper_method :user_signed_in?

def login(user)
  Current.user = user
  reset_session
  session[:user_id] = user.id
end
def logout(user)
  Current.user = nil
  reset_session
end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [ :edit, :update ]

  def new
  end
  def create
    if (user = User.find_by(email: params[:email]))
      PasswordMailer.with(
        user: user,
        token: user.generate_token_for(:password_reset)
      ).password_reset.deliver_later
    end
    redirect_to root_path, notice: "Check your email to reset your password."
  end
  def edit
  end
def update
  if @user.update(password_params)
    redirect_to new_session_path, notice: "Your password has been reset successfully. Please Login."
  else
    render edit:, status: :unprocessable_entity
  end
end
private
def set_user_by_token
  @user = User.find_by_token_for(:password_reset, params[:token])
  redirect_to new_password_resets_path alert: " Invalid token please try again." unless @user.present?
end

def password_params
  params.require(:user).permit(:password, :password_confirmation)
end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update(password_params)
      redirect_to edit_password_path, notice: "Your password has been updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end
private

def password_params
  params.require(:user).permit(
    :passsword,
    :password_confirmation,
    :password_challenge
  ).with_defaults(password_challenge: "")
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity

    end
  end
  private

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :firstname, :lastname, :role)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
 def create
   if user = User.authenticate_by(email: params[:email], password: params[:password])
     login user
     redirect_to root_path, notice: "You have signed in successfully"
   else
     flash[:alert] = "Invalid email or password."
     render :new, status: :unprocessable_entity
   end
 end
  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> AuthenticationExample </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <div> <%= notice %> </div>
    <div> <%= alert %> </div>


    <%if user_signed_in?%>
    <%= link_to "Edit Password", edit_password_path %>
    <%= button_to "Log out", session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign Up", new_registration_path %>
    <%= link_to "Log in", new_session_path %>
    <% end %>

    <%=yield %>



  </body>
</html>

app/views/main/index.html.erb
<h1>Homepage</h1>

app/views/password_resets/edit.html.erb
<h1> Reset Your Password </h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
<% if form.object.errors.any? %>
<% form.object.errors.full_messages.each do |message| %>
<div><%= message %></div>
<% end %>
<% end %>

    <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
</div>


  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
</div>

<div>
    <%= form.submit "Reset Your Password" %>
</div>

<% end %>

app/views/password_resets/new.html.erb
<h1> Reset Your Password </h1>

<%= form_with model: @user, url: password_reset_path do |form| %>
<div>
    <%= form.label :email %>
    <%= form.email_field :email%>
</div>

<div>
    <%= form.submit "Reset password" %>
</div>

<% end %>